// app/admin/staticBookings.ts

export type Booking = {
  id: string;
  name: string;
  street: string;
  address: string;
  email: string;
  phone: string;
  service: string;
  date: Date;
  time: string; // "HH:MM"
  notes?: string;
  status: "pending" | "confirmed" | "rejected";
};

export const staticBookings: Booking[] = [
  {
    id: "bk_001",
    name: "John Carter",
    street: "Main St",
    address: "123 Main St, Los Angeles, CA 90001",
    email: "john.carter@gmail.com",
    phone: "323-555-0192",
    service: "Interior Detailing",
    date: new Date("2026-02-01"),
    time: "10:30",
    notes: "Black BMW, heavy dust inside",
    status: "pending",
  },
  {
    id: "bk_002",
    name: "Maria Lopez",
    street: "Sunset Blvd",
    address: "890 Sunset Blvd, Los Angeles, CA 90028",
    email: "maria.lopez@yahoo.com",
    phone: "213-555-8821",
    service: "Full Exterior Wash",
    date: new Date("2026-02-02"),
    time: "13:00",
    notes: "White Tesla Model 3",
    status: "confirmed",
  },
  {
    id: "bk_003",
    name: "Kevin Tan",
    street: "Wilshire Blvd",
    address: "455 Wilshire Blvd, Los Angeles, CA 90017",
    email: "kevin.tan@outlook.com",
    phone: "310-555-7711",
    service: "Ceramic Coating",
    date: new Date("2026-02-03"),
    time: "09:00",
    notes: "Brand new car, prefer matte-safe products",
    status: "pending",
  },
  {
    id: "bk_004",
    name: "Alyssa Reed",
    street: "Broadway",
    address: "77 Broadway, New York, NY 10007",
    email: "alyssa.reed@gmail.com",
    phone: "917-555-3399",
    service: "Engine Bay Cleaning",
    date: new Date("2026-02-04"),
    time: "15:30",
    notes: "Please avoid high pressure near sensors",
    status: "confirmed",
  },
  {
    id: "bk_005",
    name: "Marcus Hill",
    street: "Market St",
    address: "901 Market St, San Francisco, CA 94103",
    email: "marcus.hill@gmail.com",
    phone: "415-555-6621",
    service: "Full Detail Package",
    date: new Date("2026-02-05"),
    time: "11:00",
    notes: "Dog hair in rear seats + trunk",
    status: "pending",
  },
  {
    id: "bk_006",
    name: "Nina Patel",
    street: "Santa Monica Blvd",
    address: "220 Santa Monica Blvd, Santa Monica, CA 90401",
    email: "nina.patel@gmail.com",
    phone: "424-555-1044",
    service: "Interior Detailing",
    date: new Date("2026-02-06"),
    time: "12:15",
    notes: "Coffee spill on center console",
    status: "confirmed",
  },
  {
    id: "bk_007",
    name: "Daniel Kim",
    street: "Hollywood Blvd",
    address: "680 Hollywood Blvd, Los Angeles, CA 90028",
    email: "daniel.kim@icloud.com",
    phone: "818-555-7730",
    service: "Paint Correction",
    date: new Date("2026-02-07"),
    time: "08:30",
    notes: "Swirls visible under sunlight",
    status: "pending",
  },
  {
    id: "bk_008",
    name: "Sophia Nguyen",
    street: "Figueroa St",
    address: "1200 S Figueroa St, Los Angeles, CA 90015",
    email: "sophia.nguyen@gmail.com",
    phone: "626-555-9002",
    service: "Full Exterior Wash",
    date: new Date("2026-02-08"),
    time: "16:00",
    notes: "SUV, please clean wheel wells thoroughly",
    status: "rejected",
  },
  {
    id: "bk_009",
    name: "Eric Johnson",
    street: "Ocean Ave",
    address: "50 Ocean Ave, Santa Monica, CA 90401",
    email: "eric.johnson@gmail.com",
    phone: "310-555-2201",
    service: "Ceramic Coating",
    date: new Date("2026-02-09"),
    time: "10:00",
    notes: "Needs 2-layer coating if possible",
    status: "pending",
  },
  {
    id: "bk_010",
    name: "Isabella Cruz",
    street: "Melrose Ave",
    address: "300 Melrose Ave, Los Angeles, CA 90036",
    email: "isabella.cruz@outlook.com",
    phone: "323-555-4408",
    service: "Engine Bay Cleaning",
    date: new Date("2026-02-10"),
    time: "14:15",
    notes: "Light dust only, mostly for presentation",
    status: "confirmed",
  },
  {
    id: "bk_011",
    name: "Noah Williams",
    street: "Sepulveda Blvd",
    address: "9100 Sepulveda Blvd, Los Angeles, CA 90045",
    email: "noah.williams@gmail.com",
    phone: "562-555-3320",
    service: "Paint Correction",
    date: new Date("2026-02-11"),
    time: "09:45",
    notes: "Water spots on hood and roof",
    status: "pending",
  },
  {
    id: "bk_012",
    name: "Chloe Bennett",
    street: "Ventura Blvd",
    address: "1500 Ventura Blvd, Sherman Oaks, CA 91403",
    email: "chloe.bennett@gmail.com",
    phone: "747-555-6021",
    service: "Full Detail Package",
    date: new Date("2026-02-12"),
    time: "13:30",
    notes: "Please call on arrival, gated parking",
    status: "rejected",
  },

];
